### ISSUE TITLE
pypi not avaliable

### ISSUE THREAD

**Issue by tmolbergen** [dunielpls/vitalqip-api-client#1]
Hi, 

Looks like the repo is not maintained but I'll try regardless. Would there be any chance of getting the source for this library, it has a couple of functions which looks promising for my usecase.

Thanks

**Comment by dunielpls** [comment]
Hello.

Unfortunately I have not yet had enough time on my hands to push the skeleton code to GitHub. I will finish a working but barebones version as soon as the opportunity arises.

The reason behind the repository in the first place is that I have been working on migrating a fairly volumous VitalQIP instance to a NetBox-based DDI but due to a varying level of data quality I had to focus my efforts on data science for cleaning and formatting it.

Thanks for the reminder. 😄

**Comment by tmolbergen** [comment]
Thanks for that, 

I was wondering if you could shed some light on these functions in the mean time. I've tried doing an empty search towards our QIP instance but I think the empty query might be a little bit big, essentially the query times out. We have around 20-30k subnets so i'm not surprised that it times out, but it would be interesting to see how you managed to get around the timeout. 

networks0 = qip.list_networks_v4()
subnets0 = qip.list_subnets_v4()

**Comment by tmolbergen** [comment]
In case you ever need the same thing yourself I found another way to do it; 

If you do a post request towards /qip endpoint with headers;

request.AddHeader("Accept", "*/*");
request.AddHeader("Content-Type", "application/json");
request.AddHeader("Cookie", QipCookie);

with body of; 
            
request.AddStringBody("{ \"service\": null,\"method\": \"QipList.getV4SubnetList\", \"id\":30, 


you will be returned a list of all the subnets with ip subnet and description. The lines above is just copy paste from some c# code I wrote :)

**Comment by dunielpls** [comment]
I apologise for the late response, it seems I forgot to follow up the issue. I am glad you found a way to fetch the data you needed from one of the other APIs - some of them are backed directly by command-line tools that may time out when called via the various web services.

For the record: VitalQIP, to my knowledge, uses three different APIs:
- The JSON REST API at `/json` which the web interface - and you - used,
- XML-RPC at `/qip?RPC2` used by the web interface, and
- The JSON REST API described by Swagger at `/rest-api`.

It is also possible to use various `qip-*` command-line tools at the server running the ESM software if you need to mass export data.
